name: AutoCorrect Actions
run-name: ${{ github.actor }} run AutoCorrect
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@main

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main

      - run: curl -sSL https://git.io/JcGER | bash
      - run: autocorrect -V